export type FilterKey =
  | "All Pieces"
  | "Body Wave"
  | "Pixie Curl"
  | "Silky Straight"
  | "Coily Press"
  | "New in"
  | "Bestsellers"
  | "Trending"
  | "Handpicked";

export interface Product {
  slug: string;
  name: string;
  price: string;
  priceNum: number;
  src: string;
  categories: FilterKey[];
  description: string;
  /** Local image paths for product detail page (relative to /public) */
  detailImages?: string[];
}

export const products: Product[] = [
  {
    slug: "bodie",
    name: `Bodie – Silk Straight Bob • 12"`,
    price: "₦235,000",
    priceNum: 235000,
    src: "/products/bodie-1.jpg",
    categories: ["Silky Straight", "Trending"],
    description: "Bodie arrives as a statement of precision. Twelve inches of flawless silk-straight virgin hair, cut clean at the jaw with absolute certainty. No excess, no apology — just the bob in its most refined form. Its HD lace front dissolves into the skin as though it were always there.",
  },
  {
    slug: "imani",
    name: `Imani - 22" · HD Lace`,
    price: "₦346,000",
    priceNum: 346000,
    src: "/products/imani-1.jpg",
    categories: ["Silky Straight", "Bestsellers"],
    description: "Imani is twenty-two inches of restraint and intention. Silk-straight virgin hair, hand-finished through an HD frontal that reads as bare skin. Wear it with the ends tucked or blow-brushed into a softened flare — the silhouette shifts; the elegance does not.",
    detailImages: ["/products/imani-1.jpg", "/products/imani-2.jpg", "/products/imani-3.jpg", "/products/imani-4.jpg"],
  },
  {
    slug: "camille",
    name: `Camille - Hand-finished body wave · 24"`,
    price: "₦186,000",
    priceNum: 186000,
    src: "/products/camille-1.jpg",
    categories: ["Body Wave", "New in"],
    description: "Camille is ease made beautiful. A hand-finished body wave in twenty-four inches of deeply conditioned virgin hair — the S-pattern set by hand so each wave falls with organic irregularity. Not styled into submission. Simply, perfectly, itself.",
  },
  {
    slug: "zoe",
    name: `Zoe - Polished straight finish · 26"`,
    price: "₦326,000",
    priceNum: 326000,
    src: "/products/zoe-1.jpg",
    categories: ["Silky Straight", "Trending"],
    description: "Zoe is twenty-six inches of quiet authority. Each strand lies with a polish that doesn't announce itself — it simply is. Bone-straight and luminous, with the kind of finish that reads as natural from across a room and exquisite up close.",
  },
  {
    slug: "amara",
    name: `Amara – Honey Highlighted Wave • 20"`,
    price: "₦295,000",
    priceNum: 295000,
    src: "/products/amara-1.jpg",
    categories: ["Body Wave", "Bestsellers"],
    description: "Amara holds colour the way summer does — as warmth, not excess. Honey-highlighted across twenty inches of flowing body wave, each streak placed by hand so no two sections catch the light identically. Dimensional, sun-kissed, and effortlessly beautiful.",
    detailImages: ["/products/amara-1.jpg", "/products/amara-2.jpg", "/products/amara-3.jpg", "/products/amara-4.jpg"],
  },
  {
    slug: "kiki",
    name: `Kiki – Bouncy Volumizing Curls • 14"`,
    price: "₦195,000",
    priceNum: 195000,
    src: "/products/kiki-1.jpg",
    categories: ["Pixie Curl", "New in"],
    description: "Kiki is a silhouette, not just a wig. Fourteen inches of tightly-coiled pixie curls built at full density and worn with total intention. The texture is alive — bouncing at the roots, spiralling at the ends — and the crown holds its shape through every hour of the day.",
  },
  {
    slug: "naomi",
    name: `Naomi – Luxury Deep Body Wave • 24"`,
    price: "₦385,000",
    priceNum: 385000,
    src: "/products/naomi-1.jpg",
    categories: ["Body Wave", "Bestsellers"],
    description: "Naomi is the collection's defining piece. A deep body wave in twenty-four inches of jet-black virgin hair — each crest formed with weight and deliberation. It falls with the kind of volume that changes how you enter a room. HD transparent lace. Immaculate finish. No concessions.",
    detailImages: ["/products/naomi-1.jpg", "/products/naomi-2.jpg", "/products/naomi-3.jpg", "/products/naomi-4.jpg"],
  },
  {
    slug: "sienna",
    name: `Sienna – Golden Balayage Straight • 22"`,
    price: "₦315,000",
    priceNum: 315000,
    src: "/products/sienna-1.jpg",
    categories: ["Silky Straight", "Bestsellers"],
    description: "Sienna is a colour story told in light. Golden balayage painted through twenty-two inches of bone-straight virgin hair — darker at the roots, brighter at the lengths, with a transition so seamless it reads as sun on skin rather than colour on hair.",
    detailImages: ["/products/sienna-1.jpg", "/products/sienna-2.jpg"],
  },
  {
    slug: "maya",
    name: `Maya – Wet & Wavy HD Frontal • 20"`,
    price: "₦285,000",
    priceNum: 285000,
    src: "/products/maya-1.jpg",
    categories: ["Body Wave", "Handpicked"],
    description: "Maya is transformation made tactile. Saturate it with water and the waves define themselves into textured coils dripping with dimension. Blow it dry and they soften into a full, feathered body wave. One piece; two entirely different silhouettes.",
    detailImages: ["/products/maya-1.jpg", "/products/maya-2.jpg", "/products/maya-3.jpg"],
  },
  {
    slug: "zuri",
    name: `Zuri – Premium Afro Kinky Coils • 18"`,
    price: "₦260,000",
    priceNum: 260000,
    src: "/products/zuri-1.jpg",
    categories: ["Coily Press", "Handpicked"],
    description: "Zuri is density in its purest form. Tight kinky coils at a natural 4C pattern — uniform, defined, and impossibly full — expanding generously when lifted or picked through. Eighteen inches worn loose as a crown, or gathered high as a statement. Either way, Zuri speaks.",
    detailImages: ["/products/zuri-1.jpg", "/products/zuri-2.jpg", "/products/zuri-3.jpg"],
  },
  {
    slug: "skye",
    name: `Skye – Electric Blue Custom Color • 24"`,
    price: "₦380,000",
    priceNum: 380000,
    src: "/products/skye-1.jpg",
    categories: ["Body Wave", "Handpicked"],
    description: "Skye refuses to be quiet. A custom-dyed electric blue body wave in twenty-four inches of premium virgin human hair — the pigment deposited deep into every strand so the colour stays saturated through washing, heat, and time. Worn by the woman who leads, not follows.",
    detailImages: ["/products/skye-1.jpg", "/products/skye-2.jpg"],
  },
  {
    slug: "tari",
    name: `Tari – Honey Blonde Blunt Cut • 16"`,
    price: "₦245,000",
    priceNum: 245000,
    src: "/products/tari-1.jpg",
    categories: ["Silky Straight", "Handpicked"],
    description: "Tari is precision worn lightly. Sixteen inches of honey blonde virgin hair cut to a blunt finish — the colour warm and even, the ends clean-trimmed to a sharp line. The bob sits at the shoulder like it was always supposed to be there.",
  },
  {
    slug: "kelechi",
    name: `Kelechi – Wet & Wavy Half-Up • 22"`,
    price: "₦310,000",
    priceNum: 310000,
    src: "/products/kelechi-1.jpg",
    categories: ["Body Wave", "Trending"],
    description: "Kelechi is movement that commands attention. Wet and wavy at twenty-two inches, with waves that ripple from crown to tip in a rich, dense pattern. Wear it fully down for maximum drama or half-up with the waves cascading over the twist. Either way, it turns.",
  },
  {
    slug: "tiwa",
    name: `Tiwa – Kinky Curly Fringe Puff • 14"`,
    price: "₦225,000",
    priceNum: 225000,
    src: "/products/tiwa-1.jpg",
    categories: ["Pixie Curl", "Trending"],
    description: "Tiwa is compact and entirely present. A kinky-curl puff styled to fourteen inches of maximum volume, finished with a fringe that frames the face with deliberate precision. Dense from root to end, the silhouette is round, full, and unmistakably considered.",
  },
  {
    slug: "hadassah",
    name: `Hadassah – Luxury Bone Straight • 30"`,
    price: "₦450,000",
    priceNum: 450000,
    src: "/products/hadassah-1.jpg",
    categories: ["Silky Straight", "Bestsellers"],
    description: "Hadassah is the collection's longest, most absolute piece. Thirty inches of bone-straight virgin hair pressed to a glass finish — not a single strand out of alignment. The HD transparent lace is invisible. The hair is not. Luxury without amendment.",
    detailImages: ["/products/hadassah-1.jpg", "/products/hadassah-2.jpg", "/products/hadassah-3.jpg", "/products/hadassah-4.jpg"],
  },
  {
    slug: "zara",
    name: `Zara – Caramel Balayage Straight • 24"`,
    price: "₦340,000",
    priceNum: 340000,
    src: "/products/zara-1.jpg",
    categories: ["Silky Straight", "New in"],
    description: "Zara holds warmth the way a good caramel should — rich, layered, and entirely satisfying. Twenty-four inches of sleek straight virgin hair, hand-painted from root to tip with a gradient that moves from dark to honey with no visible seam.",
  },
  {
    slug: "simi",
    name: `Simi – HD Lace Body Wave • 22"`,
    price: "₦320,000",
    priceNum: 320000,
    src: "/products/simi-1.jpg",
    categories: ["Body Wave", "New in"],
    description: "Simi is the body wave at its most considered. Twenty-two inches of deeply conditioned virgin hair in a clean, unhurried wave — each crest consistent, each trough deliberate. The HD frontal adapts to every complexion, and the construction holds through heat, humidity, and everything in between.",
    detailImages: ["/products/simi-1.jpg", "/products/simi-2.jpg", "/products/simi-3.jpg"],
  },
  {
    slug: "nini",
    name: `Nini – Ombre Volumizing Curls • 16"`,
    price: "₦245,000",
    priceNum: 245000,
    src: "/products/nini-1.jpg",
    categories: ["Pixie Curl", "Trending"],
    description: "Nini carries dimension from the roots down. An ombre that travels through sixteen inches of volumised curl — dark at the crown, lifting gradually to something lighter at the tips. Worn with the coils full or stretched, the colour reads differently in every light.",
    detailImages: ["/products/nini-1.jpg", "/products/nini-2.jpg"],
  },
  {
    slug: "dami",
    name: `Dami – Classic Bone Straight • 18"`,
    price: "₦290,000",
    priceNum: 290000,
    src: "/products/dami-1.jpg",
    categories: ["Silky Straight", "New in"],
    description: "Dami is the essential. Eighteen inches of bone-straight virgin hair in its most honest form — natural black, pressed to a mirror finish, without colour or embellishment. The piece that underpins a wardrobe. Classic by design, flawless by construction.",
  },
  {
    slug: "fola",
    name: `Fola – Premium Water Wave Bob • 14"`,
    price: "₦215,000",
    priceNum: 215000,
    src: "/products/fola-1.jpg",
    categories: ["Body Wave", "New in"],
    description: "Fola is ease worn beautifully. A water-wave bob at fourteen inches — loose, light, and free-moving. The waves sit at the shoulder with a natural looseness that feels lived-in from the moment it's placed. Nothing overdone. Nothing missing.",
  },
  {
    slug: "talia",
    name: `Talia – Highlighted Bouncy Curls • 16"`,
    price: "₦285,000",
    priceNum: 285000,
    src: "/products/talia-1.jpg",
    categories: ["Pixie Curl", "Handpicked"],
    description: "Talia's curls carry light through them. Warm highlights worked through sixteen inches of bouncy curl — placed by hand so the dimension reads naturally, as though it emerged from weeks in the sun rather than a salon chair. The coils hold their shape. The colour does the rest.",
    detailImages: ["/products/talia-1.jpg", "/products/talia-2.jpg", "/products/talia-3.jpg", "/products/talia-4.jpg"],
  },
  {
    slug: "rhea",
    name: `Rhea – Premium Afro Kinky Coils • 12"`,
    price: "₦195,000",
    priceNum: 195000,
    src: "/products/rhea-1.jpg",
    categories: ["Coily Press", "Handpicked"],
    description: "Rhea is a study in texture. Twelve compact inches of premium afro kinky coils — tight, uniform, and dense — worn as a silhouette that expands dramatically when lifted. The coils are shaped by hand and set at a natural 4C pattern. Short in length; long in presence.",
    detailImages: ["/products/rhea-1.jpg", "/products/rhea-2.jpg", "/products/rhea-3.jpg"],
  },
  {
    slug: "fiona",
    name: `Fiona – Auburn Bone Straight • 24"`,
    price: "₦395,000",
    priceNum: 395000,
    src: "/products/fiona-1.jpg",
    categories: ["Silky Straight", "Trending"],
    description: "Fiona is colour worn as restraint. A deep auburn — somewhere between mahogany and rust — pressed bone-straight through twenty-four inches of premium virgin hair. In direct light it is rich and warm. In shadow, it deepens. The drama is quiet, consistent, and entirely intentional.",
    detailImages: ["/products/fiona-1.jpg", "/products/fiona-2.jpg", "/products/fiona-3.jpg"],
  },
  {
    slug: "lyra",
    name: `Lyra – Effortless Beach Wave • 22"`,
    price: "₦310,000",
    priceNum: 310000,
    src: "/products/lyra-1.jpg",
    categories: ["Body Wave", "Trending"],
    description: "Lyra is water given form. A loose beach wave at twenty-two inches — the kind of texture that looks untouched while being precisely crafted. Full without being heavy, defined without being stiff. The piece that makes effortless look like the most deliberate choice of all.",
    detailImages: ["/products/lyra-1.jpg", "/products/lyra-2.jpg", "/products/lyra-3.jpg", "/products/lyra-4.jpg"],
  },
  {
    slug: "khadijah",
    name: `Khadijah – Premium Kinky Coils • 10"`,
    price: "₦202,000",
    priceNum: 202000,
    src: "/products/khadijah-1.jpg",
    categories: ["Coily Press", "New in"],
    description: "Khadijah is presence distilled into ten compact inches. Dense, springy kinky coils at a natural 4C pattern — built to hold their shape and expand dramatically when lifted. The silhouette is bold, the finish is clean, and the energy is entirely its own.",
    detailImages: ["/products/khadijah-1.jpg", "/products/khadijah-2.jpg", "/products/khadijah-3.jpg", "/products/khadijah-4.jpg"],
  },
  {
    slug: "tara",
    name: `Tara – Messy Pixie Curls • 12"`,
    price: "₦168,000",
    priceNum: 168000,
    src: "/products/tara-1.jpg",
    categories: ["Pixie Curl", "New in"],
    description: "Tara is the art of studied undone. Twelve inches of loose pixie curls that fall with just enough disorder to look genuinely effortless — each coil catching its own light, the fringe sitting softly at the brow. Wear it fresh or worn-in; either way, it looks right.",
  },
  {
    slug: "zainab",
    name: `Zainab – Wet & Wavy HD Frontal • 22"`,
    price: "₦272,000",
    priceNum: 272000,
    src: "/products/zainab-1.jpg",
    categories: ["Body Wave", "New in"],
    description: "Zainab plays beautifully with water. At twenty-two inches, these waves define and clump when saturated — rich, textured coils that loosen into a flowing body wave as they dry. The HD frontal is invisible at the parting; the hair is anything but.",
    detailImages: ["/products/zainab-1.jpg", "/products/zainab-2.jpg"],
  },
  {
    slug: "eniola",
    name: `Eniola – Auburn Kinky Natural • 14"`,
    price: "₦228,000",
    priceNum: 228000,
    src: "/products/eniola-1.jpg",
    categories: ["Coily Press", "New in"],
    description: "Eniola is coily texture dipped in warmth. An auburn-tinted kinky natural at fourteen inches — the colour deep and rust-toned against tight, dense coils. The kind of piece that announces itself by texture first, then by tone. Full, unconventional, and entirely considered.",
  },
  {
    slug: "nalia",
    name: `Nalia – Deep Curl HD Frontal • 20"`,
    price: "₦265,000",
    priceNum: 265000,
    src: "/products/nalia-1.jpg",
    categories: ["Body Wave", "New in"],
    description: "Nalia moves with the confidence of someone who knows exactly how she looks. Twenty inches of deep, spiralling curl — dense at the roots, tapering softly at the ends — with an HD frontal that reads as a natural hairline from every angle. Rich, full, and completely alive.",
    detailImages: ["/products/nalia-1.jpg", "/products/nalia-2.jpg", "/products/nalia-3.jpg", "/products/nalia-4.jpg"],
  },
  {
    slug: "morayo",
    name: `Morayo – Honey Straight Gloss • 24"`,
    price: "₦295,000",
    priceNum: 295000,
    src: "/products/morayo-1.jpg",
    categories: ["Silky Straight", "New in"],
    description: "Morayo is light worn as hair. Twenty-four inches of honey-toned straight virgin hair with a gloss finish that reflects differently in every setting — warm indoors, luminous in sun. The tone is rich without being brash, the straightness absolute. A statement made quietly.",
    detailImages: ["/products/morayo-1.jpg", "/products/morayo-2.jpg", "/products/morayo-3.jpg", "/products/morayo-4.jpg"],
  },
];
